# Generated by Django 4.1.3 on 2022-12-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deportes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='edad',
            field=models.IntegerField(max_length=3),
        ),
    ]
