# Generated by Django 4.1.3 on 2022-12-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_cliente_coche'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coche',
            name='marca',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='coche',
            name='matricula',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
