# Generated by Django 4.1.3 on 2022-12-01 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_coche_marca_alter_coche_matricula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coche',
            name='cliente',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Coche',
        ),
    ]
